[build]
builder = "NIXPACKS"

[deploy]
# jalan setiap start container
startCommand = """
php artisan config:cache &&
php artisan route:cache &&
php artisan storage:link || true &&
php artisan migrate --force &&
php -d variables_order=EGPCS -S 0.0.0.0:${PORT:-8080} -t public
"""
