[build]
builder = "NIXPACKS"

[deploy]
# jalankan cache + migrate, lalu start server PHP di port Railway
startCommand = "php artisan config:cache && php artisan route:cache && php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"
